# Generated by Django 4.2.1 on 2023-05-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('mrp', models.IntegerField(max_length=10)),
                ('discount_in_precentage', models.IntegerField(max_length=10, null=True)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('created_time', models.TimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
