# Generated by Django 4.2.1 on 2023-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
