# Generated by Django 4.1.7 on 2023-06-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_home', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('Expense_date', models.DateField()),
                ('description', models.TextField(max_length=250)),
                ('amount', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reimbursement',
            },
        ),
    ]
