# Generated by Django 4.1.7 on 2023-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_home', '0003_reimbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutesOfMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.TextField(max_length=100)),
                ('conductor', models.CharField(max_length=20)),
                ('conducted_date', models.DateField()),
                ('conducted_time', models.TimeField()),
                ('present_persons', models.CharField(max_length=200)),
                ('absent_persons', models.CharField(max_length=200)),
                ('discussion', models.TextField(max_length=250)),
                ('created_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'minutes_of_meeting',
            },
        ),
    ]
