# Generated by Django 4.1.7 on 2023-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_home', '0004_minutesofmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='conducted_time',
            field=models.CharField(max_length=10),
        ),
    ]
